python3.8: can't open file 'manage.py': [Errno 2] No such file or directory
python3.8: can't open file 'manage.py': [Errno 2] No such file or directory
